version: "3"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - maria_db
    links:
      - maria_db:app_db
    volumes:
      - type: bind
        source: ./Files-Upload
        target: /Files-Upload
    environment:
      MARIADB_HOST: maria_db
      MARIADB_USER: root
      MARIADB_PASSWORD: mypass
      MARIADB_PORT: 3306

  maria_db:
    image: "mariadb:10.9"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: A_ROSA_JE
      MARIADB_ROOT_PASSWORD: mypass
    volumes:
      - db:/var/lib/mysql

volumes:
  db:




